version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: base_nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./html:/usr/share/nginx/html